# -----------------------------------------------------
# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  nnoremap ,df :Denite file_rec -mode=normal<CR>
  nnoremap ,db :Denite buffer -mode=normal<CR>
  nnoremap ,dg :Denite grep -mode=normal<CR>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/neco-syntax'

# -----------------------------------------------------
# filetypes
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
  let g:vim_markdown_conceal = 0

'''

# -----------------------------------------------------
## appearance
# colorscheme
[[plugins]]
repo = 'nightsense/snow'
hook_add = '''
  if has('unix')
    set background=dark
    let g:lightline = { 'colorscheme': 'snow_dark' }
  elseif has('win64')
    set termguicolors
    set background=light
    let g:lightline = { 'colorscheme': 'snow_light' }
  endif

  colorscheme snow
'''

# visualization of indent
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_char = '|'
  let g:indentLine_color_term = 7
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

# -----------------------------------------------------
## viewr
# preview
[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'
hook_add = '''
  augroup PrevimSettings
    autocmd!
    autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
  augroup END

  nnoremap ,md :PrevimOpen
'''

# browser
[[plugins]]
repo = 'tyru/open-browser.vim'

# filer
[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
  nnoremap ,fi :Vaffle<CR>
  let g:vaffle_auto_cd = 1
  let g:vaffle_show_hidden_files = 1
  let g:vaffle_open_selected_vsplit_position = 'rightbelow'

  function! s:customize_vaffle_mappings() abort 
    nmap <buffer> <CR> <Plug>(vaffle-open-selected-vsplit)
  endfunction

  augroup vimrc_vaffle
    autocmd!
    autocmd FileType vaffle call s:customize_vaffle_mappings()
  augroup END
'''

# -----------------------------------------------------
## etc
# quick run program
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {'*': {'hook/time/enable': '1'},}
  nnoremap ,qr :QuickRun
'''

# doc
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
