# -----------------------------------------------------
## Shogo's plugins
# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

# -----------------------------------------------------
# filetypes
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'

# -----------------------------------------------------
## appearance
# colorscheme
[[plugins]]
repo = 'nightsense/snow'

# visualization of indent
[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'cohama/lexima.vim'

# -----------------------------------------------------
## viewr
# preview
[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'

# browser
[[plugins]]
repo = 'tyru/open-browser.vim'


# -----------------------------------------------------
## etc
# quick run program
[[plugins]]
repo = 'thinca/vim-quickrun'

# doc
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
